---
- name: Backup WebSphere directories if upgrade is needed
  ansible.builtin.shell: >
    tar -czf "{{ backup_dir }}/websphere_backup.tar.gz" -C "{{ install_directory }}" .
  when: websphere_installed | bool
